
CREATE DATABASE PjtoLudoIII

USE PjtoLudoIII
	
CREATE TABLE UF
(
	cdUF 			INT PRIMARY KEY,
	sgUF 			CHAR (2),
	nmUF 			VARCHAR(50)
)


CREATE TABLE CIDADE
(	
	cdUF 			INT FOREIGN KEY REFERENCES UF,
	cdCidade 		INT PRIMARY KEY , 
	nmCidade 		VARCHAR(100)
)

CREATE TABLE BAIRRO
(
	cdBairro 		INT PRIMARY KEY, 
	nmBairro 		VARCHAR(100),
	cdCidade 		INT FOREIGN KEY REFERENCES CIDADE
)

CREATE TABLE LOGRADOURO
(
	cdLogradouro 	INT PRIMARY KEY, 
	cdBairro		INT FOREIGN KEY REFERENCES BAIRRO,
	nmLogradouro	VARCHAR(300),
	noCEP 			VARCHAR(10)
) 

CREATE TABLE  PERFIL
(
	idPerfil		 		INT IDENTITY PRIMARY KEY,
	nmPerfil				VARCHAR(10) NOT NULL
)

	
CREATE TABLE  USUARIO
(
	idUsuario 		INT IDENTITY PRIMARY KEY,
	nmLogin			VARCHAR (7) NOT NULL,
	Senha		 	CHAR (8) NOT NULL,
	Ativo			BIT NOT NULL,
	idPerfil 		INT FOREIGN KEY REFERENCES PERFIL,
	noCPF			CHAR (11) UNIQUE NOT NULL,
	DtCad			SMALLDATETIME NOT NULL,
)	

CREATE TABLE CARGO
	(
		cdCargo 	INT IDENTITY PRIMARY KEY,
		nmCargo 	VARCHAR (20) NOT NULL,
	)
	
CREATE TABLE FUNCIONARIO
	( 
		cdFunc 		INT IDENTITY PRIMARY KEY,
		Nome 		VARCHAR (70) NOT NULL,
		DtNasc 		DATE NOT NULL,
		noCPF 		CHAR (11) UNIQUE NOT NULL,
		Sexo 		CHAR(1) NOT NULL,
		noCEP 		CHAR (8) NOT NULL,
		noLog 		VARCHAR (8) NOT NULL,
		Complemento VARCHAR (70),
		DDD			CHAR(2) NOT NULL,
		Telefone	VARCHAR (9)NOT NULL,
		DtEntrada 	DATE NOT NULL,
		CdCargo 	INT FOREIGN KEY REFERENCES CARGO,
		Foto 		VARCHAR (100),
		DtCad		DATE,
		Ativo		BIT NOT NULL
	)
	
	
				
CREATE TABLE CLIENTE
	( 
		cdCli 		INT IDENTITY PRIMARY KEY,
		PNome  		VARCHAR (30),
		UNome		VARCHAR (40),
		Email		VARCHAR (70) UNIQUE,
		Senha		VARCHAR (8),
		DtCad		DATE,
		Ativo		BIT NOT NULL
	)
	

	
CREATE TABLE CLIENTE_ENDERECO
(	
		cdCli_ENDERECO	INT IDENTITY PRIMARY KEY,
		cdCli 			INT FOREIGN KEY REFERENCES CLIENTE,
		PNomeDest		VARCHAR (30),
		UNomeDest		VARCHAR (40),
		DDD				CHAR (2) ,
		Telefone		VARCHAR (9) ,
		noCEP 			CHAR (8) ,
		noLog 			VARCHAR (8) ,
		Complemento		VARCHAR (70),
		PEntrega		BIT,
		DtCad			DATE,
		Ativo			BIT 
)


		
CREATE TABLE TRANSPORTADORA
	(
		cdTransp 		INT IDENTITY PRIMARY KEY,
		RazaoSocial   	VARCHAR (70) NOT NULL,
		NmFantasia    	VARCHAR (70),
		CNPJ 			CHAR (14) UNIQUE NOT NULL,
		CEP 			CHAR (8) NOT NULL,
		noLog 			VARCHAR (8) NOT NULL,
		Complemento 	VARCHAR (70),
		DDD 			CHAR (2)NOT NULL,
		Telefone 		VARCHAR (9) NOT NULL,
		HomePage 		VARCHAR(100),
		Contato 		VARCHAR (70),
		Email			VARCHAR (70),
		DDDCel			CHAR (2),
		Celular	 		VARCHAR (9),
		DtCad		    DATE,
		Ativo			BIT NOT NULL
	)
		INSERT INTO TRANSPORTADORA VALUES ( 'ARGOS LOGISTICA LTDA' , '********' , '04963798000128' , '06460030' , '1411' , 'MODULO 11' , '11' , '41332255' , 'www.grupoargos.com.br' , 'JOSE' , 'argos@grupoargos.com.br' , '11' , '66666666' , '05/06/2012 17:24:57' , 'True'  )

		




CREATE TABLE PLATAFORMA
	(
		cdPlataforma 	INT IDENTITY PRIMARY KEY,
		nmPlataforma 	VARCHAR (20) NOT NULL,
		iconePlataforma VARCHAR (20)
	)
	
	INSERT INTO PLATAFORMA VALUES ('Xbox 360','icon_Xbox_360.gif')
	INSERT INTO PLATAFORMA VALUES ('PlayStation 3','icon_ps3.gif')
	INSERT INTO PLATAFORMA VALUES ('Wii U','icon_Wii_U.gif')
	INSERT INTO PLATAFORMA VALUES ('Wii','icon_Wii.gif')
	INSERT INTO PLATAFORMA VALUES ('3DS','icon_3ds.gif')
	INSERT INTO PLATAFORMA VALUES ('PlayStation Vita','icon_PS_Vita.gif')
	INSERT INTO PLATAFORMA VALUES ('PC','icon_PC.gif')


CREATE TABLE CATEGORIA
	(
		cdCategoria 	INT IDENTITY PRIMARY KEY,
		nmCategoria 	VARCHAR (20) NOT NULL,
	)
	
	INSERT INTO CATEGORIA VALUES ('JOGO')
	INSERT INTO CATEGORIA VALUES ('CONSOLE')
	INSERT INTO CATEGORIA VALUES ('ACESSÓRIO')

CREATE TABLE SUBCATEGORIA
	(
		cdSubCategoria 	INT IDENTITY PRIMARY KEY,
		nmSubCategoria 	VARCHAR (40) NOT NULL,
	)
	
INSERT INTO SUBCATEGORIA VALUES	('Baterias') 
INSERT INTO SUBCATEGORIA VALUES ('Carregadores')
INSERT INTO SUBCATEGORIA VALUES ('Cabos')
INSERT INTO SUBCATEGORIA VALUES ('Adaptadores')
INSERT INTO SUBCATEGORIA VALUES ('Cameras')
INSERT INTO SUBCATEGORIA VALUES ('Webcams')
INSERT INTO SUBCATEGORIA VALUES ('Controles')
INSERT INTO SUBCATEGORIA VALUES ('Sistemas de Refrigeração')
INSERT INTO SUBCATEGORIA VALUES ('Sistemas de Jogo')
INSERT INTO SUBCATEGORIA VALUES ('Móveis de jogos')
INSERT INTO SUBCATEGORIA VALUES ('Headsets') 
INSERT INTO SUBCATEGORIA VALUES ('Microfones')
INSERT INTO SUBCATEGORIA VALUES ('Teclado')
INSERT INTO SUBCATEGORIA VALUES ('Mouse')
INSERT INTO SUBCATEGORIA VALUES ('Memória')
INSERT INTO SUBCATEGORIA VALUES ('Montagens') 
INSERT INTO SUBCATEGORIA VALUES ('Suportes')
INSERT INTO SUBCATEGORIA VALUES ('Reparo') 
INSERT INTO SUBCATEGORIA VALUES ('Limpeza')
INSERT INTO SUBCATEGORIA VALUES ('Armazenamento') 
INSERT INTO SUBCATEGORIA VALUES ('Gabinetes')
INSERT INTO SUBCATEGORIA VALUES ('Video') 
INSERT INTO SUBCATEGORIA VALUES ('Placas de Som')
INSERT INTO SUBCATEGORIA VALUES ('Kinect')
INSERT INTO SUBCATEGORIA VALUES ('Move')
INSERT INTO SUBCATEGORIA VALUES ('Outros')

CREATE TABLE ESRB
	(
		cdESRB 	INT IDENTITY PRIMARY KEY,
		nmESRB 	VARCHAR (40) NOT NULL,
		iconeESRB VARCHAR (40) NOT NULL
	)
	
	INSERT INTO ESRB VALUES ('Infantil','ESRB_Early_Childhood.png')
	INSERT INTO ESRB VALUES ('Adolescente','ESRB_Teen.png')
	INSERT INTO ESRB VALUES ('Somente para Adultos 18+','ESRB_Adults_Only_18+.png')
	INSERT INTO ESRB VALUES ('Todos','ESRB_Everyone.png')	
	INSERT INTO ESRB VALUES ('Jovens 17+','ESRB_Mature_17+.png')
	INSERT INTO ESRB VALUES ('Classificação Pendente','ESRB_RP.png')	
	
	
	
	
CREATE TABLE PUBLICADOR
	(
		cdPUBLICADOR 	INT IDENTITY PRIMARY KEY,
		nmPUBLICADOR 	VARCHAR (40) NOT NULL,
	)
	
	INSERT INTO PUBLICADOR VALUES ('MICROSOFT')
	INSERT INTO PUBLICADOR VALUES ('SONY')
	INSERT INTO PUBLICADOR VALUES ('NINTENDO')
	INSERT INTO PUBLICADOR VALUES ('THQ')
	INSERT INTO PUBLICADOR VALUES ('Bethesda Softworks')
	INSERT INTO PUBLICADOR VALUES ('Square Enix')
	INSERT INTO PUBLICADOR VALUES ('Deep Silver')
	INSERT INTO PUBLICADOR VALUES ('Activision')
	INSERT INTO PUBLICADOR VALUES ('505 Games')
	
	
CREATE TABLE DESENVOLVEDOR
	(
		cdDESENVOLVEDOR	INT IDENTITY PRIMARY KEY,
		nmDESENVOLVEDOR 	VARCHAR (40) NOT NULL,
	)
	
	INSERT INTO DESENVOLVEDOR VALUES ('MICROSOFT')
	INSERT INTO DESENVOLVEDOR VALUES ('SONY')
	INSERT INTO DESENVOLVEDOR VALUES ('NINTENDO')
		INSERT INTO DESENVOLVEDOR VALUES ('THQ')
		INSERT INTO DESENVOLVEDOR VALUES ('Bethesda Softworks')
		INSERT INTO DESENVOLVEDOR VALUES ('Square Enix')
		INSERT INTO DESENVOLVEDOR VALUES ('Deep Silver')
		INSERT INTO DESENVOLVEDOR VALUES ('Activision')
		INSERT INTO DESENVOLVEDOR VALUES ('505 Games')	
		
CREATE TABLE MIDIA
	(
		cdMidia 	INT IDENTITY PRIMARY KEY,
		nmMidia 	VARCHAR (20) NOT NULL,
	)
	
	INSERT INTO MIDIA VALUES ('BLU-RAY')
	INSERT INTO MIDIA VALUES ('DVD')
	INSERT INTO MIDIA VALUES ('UMD')
	INSERT INTO MIDIA VALUES ('CARTUCHO')
	
CREATE TABLE GENERO
	(
		cdGenero 	INT IDENTITY PRIMARY KEY,
		nmGenero 	VARCHAR (20) NOT NULL,
	)
	
	INSERT INTO GENERO VALUES ('Ação')
	INSERT INTO GENERO VALUES ('Aventura')
	INSERT INTO GENERO VALUES ('Esporte')
	INSERT INTO GENERO VALUES ('Estratégia/RPG')
	INSERT INTO GENERO VALUES ('Futebol')
	INSERT INTO GENERO VALUES ('Infantil')
	INSERT INTO GENERO VALUES ('Luta')
	INSERT INTO GENERO VALUES ('Musical')
	INSERT INTO GENERO VALUES ('Simulação')
	INSERT INTO GENERO VALUES ('Outros')
	INSERT INTO GENERO VALUES ('Tiro')
	
	
	
	
	

	
	
	

	CREATE TABLE SITUACAO
	(
		cdSit 			INT IDENTITY PRIMARY KEY,
		Situacao 		VARCHAR (20) NOT NULL
	)

	INSERT INTO SITUACAO VALUES ('NOVO')
	INSERT INTO SITUACAO VALUES ('FATURADO')
	INSERT INTO SITUACAO VALUES ('ENVIADO')
	INSERT INTO SITUACAO VALUES ('FECHADO')
	INSERT INTO SITUACAO VALUES ('CANCELADO')
		
			
	create TABLE PEDCOMPRA
(
	cdPedCompra		INT IDENTITY PRIMARY KEY,
	CNPJ 			CHAR (14) FOREIGN KEY REFERENCES FORNECEDOR,
	idUsuario		INT FOREIGN KEY REFERENCES USUARIO,
	dtPedido 		SMALLDATETIME NOT NULL,
	cdSit 			INT FOREIGN KEY REFERENCES SITUACAO,
	Ativo			BIT NOT NULL
) 



CREATE  TABLE DET_PEDCOMPRA
(
	cdDetPedCompra 	INT IDENTITY PRIMARY KEY,
	cdPedCompra 	INT FOREIGN KEY REFERENCES PEDCOMPRA,
	EAN 		   VARCHAR(14)FOREIGN KEY REFERENCES PRODUTO,
	QTDE 			VARCHAR (10) NOT NULL,
	CustoUnit		DECIMAL (8,2) NOT NULL,
	Entregue		BIT NOT NULL,
	Ativo			BIT NOT NULL
)

CREATE TABLE ENTNF
	(
	cdEntNF			INT IDENTITY PRIMARY KEY,
	cdPedCompra 	INT FOREIGN KEY REFERENCES PEDCOMPRA,
	CNPJ 			CHAR(14) FOREIGN KEY REFERENCES FORNECEDOR,
	dtRecebimento	SMALLDATETIME,
	noNF			VARCHAR(15),
	vlNF		  	DECIMAL (8,2), 
	dtEmissao		SMALLDATETIME ,
	idUsuario		INT FOREIGN KEY REFERENCES USUARIO
	)
	
	CREATE  TABLE DET_ENTNF
(
	cdDetEntNF		INT IDENTITY PRIMARY KEY,
	cdEntNF 		INT FOREIGN KEY REFERENCES ENTNF,
	cdProduto	INT FOREIGN KEY REFERENCES PRODUTO,
	QTDE 			VARCHAR (10) NOT NULL,
	CustoUnit		DECIMAL (8,2) NOT NULL,
)


CREATE TABLE TPVENDA
	(
		cdTPvenda 	INT IDENTITY PRIMARY KEY,
		TPvenda 	VARCHAR (20) NOT NULL
	)

	INSERT INTO TPVENDA VALUES ('Balcão')	
	INSERT INTO TPVENDA VALUES ('Telefone')	
	INSERT INTO TPVENDA VALUES ('Internet')
	
CREATE TABLE FORMAPGTO
	(
		cdFormaPgto INT IDENTITY PRIMARY KEY,
		nmFormaPgto	VARCHAR (20) NOT NULL
	)
	
	INSERT INTO FORMAPGTO VALUES ('Dinheiro')
	INSERT INTO FORMAPGTO VALUES ('Cartão')	
	
CREATE TABLE PDV
(
	cdPDV 			INT IDENTITY PRIMARY KEY,
	cdFunc 			INT FOREIGN KEY REFERENCES USUARIO,
	cdCli 			INT FOREIGN KEY REFERENCES CLIENTE,
	dtPedido 		SMALLDATETIME NOT NULL,
	dtEnvio 		SMALLDATETIME ,
	cdTransp 		INT FOREIGN KEY REFERENCES TRANSPORTADORA,
	txEnvio			DECIMAL (8,2), 
	obs 			VARCHAR (300),
	cdSit 			INT FOREIGN KEY REFERENCES SITUACAO ,
	cdTPvenda 		INT FOREIGN KEY REFERENCES TPVENDA ,
	cdFormaPgto 	INT FOREIGN KEY REFERENCES FORMAPGTO,
	Ativo			BIT NOT NULL 
) 

CREATE TABLE DET_PDV
(
	cdDetPDV 		INT IDENTITY PRIMARY KEY,
	cdPDV 			INT FOREIGN KEY REFERENCES PDV,
	EAN	    		VARCHAR (14) FOREIGN KEY REFERENCES PRODUTO,
	QTDE 			INT NOT NULL,
	SubTotal 		DECIMAL (8,2) NOT NULL,
	)
	


CREATE TABLE TIPO_ME
(
	cdTPMe 		INT IDENTITY PRIMARY KEY,
	noDetME 	VARCHAR (30) NOT NULL,
)
	INSERT INTO TIPO_ME VALUES ('ENTRADA')
	INSERT INTO TIPO_ME VALUES ('SAIDA')
	INSERT INTO TIPO_ME VALUES ('RESERVADO')
	
	
CREATE TABLE DET_ME
(
	cdDetMe 	INT IDENTITY PRIMARY KEY,
	noDetME 	VARCHAR (30) NOT NULL,
)
	INSERT INTO DET_ME VALUES ('NF')
	INSERT INTO DET_ME VALUES ('VENDA')
	INSERT INTO DET_ME VALUES ('ACERTO ESTOQUE')
	INSERT INTO DET_ME VALUES ('INVENTARIO')
	
	
 CREATE TABLE MOV_EST
(
	cdMovEst	INT IDENTITY PRIMARY KEY,
	EAN	    	VARCHAR (14) FOREIGN KEY REFERENCES PRODUTO,
	QTDE		INT NOT NULL,
	cdTPMe 		INT FOREIGN KEY REFERENCES TIPO_ME,
	cdDetMe 	INT FOREIGN KEY REFERENCES DET_ME,
	DtME 		SMALLDATETIME NOT NULL,
	DtMod	 	SMALLDATETIME ,
	cdPDV 		INT,
	cdEntNF		INT,
	Ativo		BIT NOT NULL
)


